#pragma once

#define VUI_VER_MAJOR 1
#define VUI_VER_MINOR 0
#define VUI_VER_PATCH 2
#define VUI_VER_BUILD 2

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define VUI_FILEVER      VUI_VER_MAJOR, VUI_VER_MINOR, VUI_VER_PATCH, VUI_VER_BUILD
#define VUI_FILEVER_STR  STR(VUI_VER_MAJOR) "." STR(VUI_VER_MINOR) "." STR(VUI_VER_PATCH) "." STR(VUI_VER_BUILD)
